export const PRODUCT_NAME = 'Markets Forge'
export const PRODUCT_DOMAIN = 'marketsforge.net'
export const PRODUCT_TAGLINE = 'Learn markets. Trade paper. Build conviction.'
export const GITHUB_FRONTEND_URL = 'https://github.com/SakthidharranR/stock-frontend'
export const GITHUB_BACKEND_URL = 'https://github.com/SakthidharranR/stock-backend'
